apiVersion: v1
kind: Secret
metadata:
  name: cluster-v33-sa              # Format <clustername>-sa
  namespace: test-ns                # vSphere Namespace where VKS cluster will be created
type: cluster.x-k8s.io/secret
stringData:    # Update with new tls key pair
  tls.crt: |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA7ZP1d2ev0a0RvxdM1Kr0
    pZbBoYwDdWtgeOAeGm2C1lFbHt5RU4zdUoPTW6ciSIhjnuslWyW0oGeuAbDo6s5J
    ......
    -----END PUBLIC KEY-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQDtk/V3Z6/RrRG/
    F0zUqvSllsGhjAN1a2B44B4abYLWUVse3lFTjN1Sg9NbpyJIiGOe6yVbJbSgZ64B
    ......
    -----END PRIVATE KEY-----
