# Example Service Account Secrets for Cluster
#
# DISCLAIMER: This script is provided "as is" without warranty.
# Use at your own risk. Not supported.
#
# These secrets MUST be created BEFORE the Cluster object.
# CAPI will use these pre-created secrets instead of generating new keys.
#.
# Generate RSA key pair:
#   openssl genrsa -out sa.key 4096
#   openssl rsa -in sa.key -pubout -out sa.pub
#
# Create the secret in the vSphere namespace of the cluster.  This will be picked up on the cluster and created as a service account
apiVersion: v1
kind: Secret
metadata:
  name: test-svc-cluster-330-sa     # Format <clustername>-sa
  namespace: test-ns                # vSphere Namespace where VKS cluster will be created
type: cluster.x-k8s.io/secret
stringData:
  tls.crt: |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA3k90B+q46FD62rzZCqsy
    ..............
    -----END PUBLIC KEY-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJRAIBADANBgkqhkiG9w0BAQEFAASCCS4wggkqAgEAAoICAQDeT3QH6rjoUPra
    ...............
    -----END PRIVATE KEY-----
---
# Example Cluster Manifest for Supervisor Cluster
#
# This file creates a workload cluster in the VKS supervisor cluster.
# Apply this to the SUPERVISOR cluster, not the workload cluster.
#
# Prerequisites:
# 1. Secret above correct Key pair updated and created in the correct namespace and name <clustername>-sa
# 2. Custom ClusterClass applied to supervisor (svc-account-issuer-custom-class-3.3.0.yaml)
# 3. Update .metadata.namespace to your vSphere namespace
# 4. Update storageclass to match your available storageclass
#
# Usage:
#    # First, edit the secrets above with your actual keys
#    kubectl apply -f test-svc-cluster.yaml

#
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: test-svc-cluster-330
  namespace: test-ns               # update to match your vsphere namespace
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["198.51.100.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  topology:
    # Set to your custom cluster class name
    class: svc-account-issuer-custom-class-v3.3.0
    version: v1.32.7---vmware.3-fips-vkr.1
    controlPlane:
      replicas: 1
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
    workers:
      machineDeployments:
        - class: node-pool
          name: np01
          replicas: 2
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
    variables:
    # Default Value can be updated at cluster build or patched
      - name: serviceAccountIssuer
        value: "https://kubernetes.default.svc.cluster.local"
      - name: vmClass
        value: best-effort-medium                                # verify vsphere namespace contains this vmclass
      - name: storageClass
        value: vsan-default-storage-policy                       # update to match available storageclass
      - name: vsphereOptions
        value:
          persistentVolumes:
            defaultStorageClass: vsan-default-storage-policy     # update to match available storageclass

