# Example Service Account Secrets for Cluster
#
# DISCLAIMER: This script is provided "as is" without warranty.
# Use at your own risk. Not supported.
#
# These secrets MUST be created BEFORE the Cluster object.
# CAPI will use these pre-created secrets instead of generating new keys.
#.
# Generate RSA key pair:
#   openssl genrsa -out sa.key 4096
#   openssl rsa -in sa.key -pubout -out sa.pub
#
# Create the secret in the vSphere namespace of the cluster.  This will be picked up on the cluster and created as a service account
apiVersion: v1
kind: Secret
metadata:
  name: cluster-v33-sa     # Format <clustername>-sa
  namespace: test-ns                # vSphere Namespace where VKS cluster will be created
type: cluster.x-k8s.io/secret
stringData:
  tls.crt: |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA3k90B+q46FD62rzZCqsy
    ..............
    -----END PUBLIC KEY-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJRAIBADANBgkqhkiG9w0BAQEFAASCCS4wggkqAgEAAoICAQDeT3QH6rjoUPra
    ...............
    -----END PRIVATE KEY-----
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cluster-v33
  namespace: test-ns
spec:
  clusterNetwork:
    services:
      cidrBlocks:
        - 198.202.0.0/16
    pods:
      cidrBlocks:
        - 193.1.0.0/16
  topology:
    class: custom-cc-service-account-v33
    version: v1.32.7---vmware.3-fips-vkr.1
    controlPlane:
      replicas: 1
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=photon
    workers:
      machineDeployments:
        - class: node-pool
          name: worker
          replicas: 1
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=photon
    variables:
      - name: vmClass
        value: best-effort-medium
      - name: storageClass
        value: vsan-default-storage-policy
      - name: vsphereOptions
        value:
          persistentVolumes:
            defaultStorageClass: vsan-default-storage-policy
            availableStorageClasses:
              - vsan-default-storage-policy
      # externalServiceAccountIssuerURL intentionally omitted
